### PR TITLE
First portion of fixes after review

### PR DESCRIPTION
**Pull request by mbakholdina**

### CODE REVIEW

**Comment by mbakholdina** [comment]
@maxsharabayko Once you have time, please build txt and PDF for me so I can check that the changes are correct. Then we can merge.

**Comment by maxsharabayko** [comment]
- Changing workgroup from MOPS to "Network Working Group" potentially requires to change the name of the document [sharabayko-mops-srt](https://datatracker.ietf.org/doc/draft-sharabayko-mops-srt/). It can therefore block update to version 03, because it will not be considered as a new version, but as a new document.
To be confirmed.

**Comment by maxsharabayko** [comment]
[draft-sharabayko-mops-srt-pr73.pdf](https://github.com/Haivision/srt-rfc/files/5464341/draft-sharabayko-mops-srt-pr73.pdf)

**Comment by mbakholdina** [comment]
@maxsharabayko Can be merged in master. Let's not revert the changes regarding Network Working Group, I've made a note regarding this.

**Pull request merged**
